apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-api-18943
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-api-18943
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
